language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
matrix:
  include:
    - php: 5.2
      dist: precise
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: precise
    - php: 5.5
      dist: precise
    - php: 5.6
      dist: precise
before_install: |
  if [ ${TRAVIS_PHP_VERSION:0:3} == "5.3" ]; then
    pecl install phar
  fi
install: |
  if [ ${TRAVIS_PHP_VERSION:0:3} == "5.2" ]; then
    export X="$HOME/.idiorm/bin"
    mkdir -p "$X"
    curl -sSfL https://github.com/treffynnon/php5.2-phpunit3.6.12-phar/releases/download/1.0.2/php52-phpunit.phar -o "$X/phpunit"
    chmod +x "$X/phpunit"
  fi
  if [ ${TRAVIS_PHP_VERSION:0:3} == "5.3" ] || [ ${TRAVIS_PHP_VERSION:0:3} == "5.4" ] || [ ${TRAVIS_PHP_VERSION:0:3} == "5.5" ] || [ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]; then
    composer require phpunit/phpunit 4.8 --dev --no-update
    composer install
  fi
  if [ ${TRAVIS_PHP_VERSION:0:1} == "7" ]; then
    composer install
  fi
script: |
  if [ ${TRAVIS_PHP_VERSION:0:3} == "5.2" ]; then
    $X/phpunit --colors --coverage-text
  else
    composer run-script test -- --colors --coverage-text
  fi
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.idiorm
    - vendor